### ISSUE TITLE
Infinite scrollable area created at the bottom of the Ghost editor

### ISSUE THREAD

**Issue by stromfeldt** [Automattic/harper#1690]
**Describe the bug**
When scrolling to the bottom of a post being edited in the Ghost publishing platform one is unable to reach the end due to an infinite scrollable area that mysteriously exists. In some cases the final element (an HTML card when I've seen this occur) is unreachable as it lays beyond the infinite scrollable area, other times the infinite scrollable area exists beyond the final element (a paragraph or what have you).

**To Reproduce**
1. Open up a (pre-written) post in the editor of the Ghost publishing platform
2. Try scrolling to the very bottom
3. See that one can infinitely scroll, in some cases not reaching the final element/paragraph in the post

**Expected behavior**
The end of the post in Ghost's editor should be reachable

**Platform**
Harper 0.55.0 / Firefox 141.0 / Ghost 6.0 / macOS 15.6

**Comment by elijah-potter** [comment]
Thanks for letting us know! I'll admit that's probably not a great look. I'm going to try to replicate it now.

**Comment by elijah-potter** [comment]
I believe this has been solved. I'll check back in when we have a new release available to confirm.

**Comment by stromfeldt** [comment]
Hello @elijah-potter, thanks very much for addressing this so quickly.

I can confirm that with 0.56.0 that the infinite scroll issue has been resolved, although a new issue seems to have been introduced. That is, a secondary scroll bar on the right appears, disappears, jumps in and out... you can see in the following videos.

In this video with nothing but text, the additional scroll bar is present at the very beginning, but then disappears and doesn't seem to return:

https://github.com/user-attachments/assets/bab00b18-0fe6-4599-8c89-66313ff8e4ed

In this one the scroll bar pops in and out rather jarringly. I'm sure you'd be better at deducing why that is than me, my only guess being that more Harper markup has some kind of effect.

https://github.com/user-attachments/assets/94b8ba44-4e58-4159-bd19-aa53c2b6c6e9

Please let me know if there's anything you'd like me to test out if it might add more clarification.

**Comment by elijah-potter** [comment]
I _think_ this has been resolved in the latest version of Harper. Mind giving it a whirl?

**Comment by stromfeldt** [comment]
I would say not really, as although there's no more flickering, that's effectively because the Harper highlighting only appears in the title and excerpt area, not in the body of the post:

![Image](https://github.com/user-attachments/assets/fc600dd9-85d6-48a3-9c52-4fa3bac0ee73)

**Comment by hippietrail** [comment]
> I would say not really, as although there's no more flickering, that's effectively because the Harper highlighting only appears in the title and excerpt area, not in the body of the post:
> 
> ![Image](https://github.com/user-attachments/assets/fc600dd9-85d6-48a3-9c52-4fa3bac0ee73)

How big is the body? Harper will not lint if a document is beyond a certain size in bytes. You can set that limit in the preferences too.

**Comment by stromfeldt** [comment]
> How big is the body? Harper will not lint if a document is beyond a certain size in bytes. You can set that limit in the preferences too.

Five paragraphs. I tried cutting it down to one paragraph just now, but the problem persists.

**Comment by elijah-potter** [comment]
I've tested this with #1970 on a local installation of Ghost, and I'm not seeing this issue anymore. When it gets merged, I'll check back in here.
