### ISSUE TITLE
Obsidian plugin merge conflicts every time there's an update

### ISSUE THREAD

**Issue by dotfrag** [Automattic/harper#2089]
**Describe the bug**

Whenever the Obsidian Harper plugin has an update, the `.obsidian/plugins/harper/data.json` file is updated, and there seem to be two issues.

1. Some settings in that file, i.e. `"AsWell": null,` are getting "randomly" removed/added back in. Maybe that's intentional part of the update? That's not technically causing any problems, but:
2. The real problem is that the `userDictionary` array gets reordered every time, causing merge conflicts when trying to synchronize my repo across different machines.

**To Reproduce**

I don't have precise steps but I hope the above explanation is adequate.

**Expected behavior**

Not expected as such, but my recommendation would be for the `userDictionary` array to be automatically sorted to a-z every time there's an update or a word is added/removed, so that git can figure out the changes and not cause merge conflicts.

**Platform**

Obsidian using git repo.

**Comment by elijah-potter** [comment]
I believe we fixed this problem a while ago, but it's possible is has resurfaced. Can you confirm which version you're using?

**Comment by dotfrag** [comment]
Hey, thanks for the prompt response. I am currently on 0.68 but this has been definitely happening since 0.66, and maybe earlier too, maybe 0.62 even, but don't take my word for it.

**Comment by dotfrag** [comment]
@elijah-potter do you know at which version this happened? I suspect I might have an issue on my end and the versions I reported might be wrong.

Edit: even if I was wrong, I tested again and confirm that I am absolutely using 0.68 and it's still happening.

**Comment by elijah-potter** [comment]
This was quite a while ago, probably around `v0.30.0`. This is definitely a regression.

**Comment by elijah-potter** [comment]
I've gone ahead and implemented a fix for this, which has since appeared in `v0.70.0`. Would you mind giving it a whirl when the next release is out, so we can confirm the absence of merge conflicts?

**Comment by dotfrag** [comment]
I've been using it without any problem across 3 machines so far, thanks!

**Comment by elijah-potter** [comment]
That's great to hear! Thanks again for letting us know about it.
